# Generated by Django 2.2.1 on 2019-06-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örnek: "2019 - 2020" ', max_length=255, verbose_name='Adı')),
                ('archive', models.BooleanField(default=False, verbose_name='Arşivlensin mi?')),
            ],
            options={
                'verbose_name': 'Dönem',
                'verbose_name_plural': 'Dönemler',
            },
        ),
    ]
