# Generated by Django 2.2.1 on 2019-06-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='business', to='members.Member', verbose_name='Yetkili'),
        ),
    ]
