# Generated by Django 2.2.1 on 2019-06-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('businesses', '0004_studentqualification_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='teachers.Teacher', verbose_name='Koordinatör Öğretmen'),
        ),
    ]
