# Generated by Django 2.2.1 on 2019-06-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_business'),
        ('businesses', '0005_business_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Yaz', 'Yaz'), ('Kış', 'Kış')], max_length=3, verbose_name='Grup')),
                ('period', models.CharField(blank=True, choices=[('1', 'P.tesi, Salı, Çarşamba'), ('2', 'Çarşamba, Perşembe, Cuma')], max_length=1, null=True, verbose_name='Haftalık Periyot')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='businesses.Business', verbose_name='İşletme')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='students.Student', verbose_name='Öğrenci')),
            ],
        ),
    ]
