# Generated by Django 2.2.1 on 2019-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='student_thoughts',
            field=models.TextField(blank=True, null=True, verbose_name='Öğrencinin düşünceleri'),
        ),
    ]
