# Generated by Django 2.2.1 on 2019-06-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Tel')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='members.Member', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Öğretmen',
                'verbose_name_plural': 'Öğretmenler',
            },
        ),
    ]
