# Generated by Django 2.2.1 on 2019-06-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='business',
        ),
        migrations.RemoveField(
            model_name='member',
            name='student',
        ),
    ]
