# Generated by Django 2.2.1 on 2019-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190605_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('Chief', 'Alan Şefi'), ('Coordinator', 'Koordinator Öğretmen'), ('Student', 'Öğrenci'), ('Business', 'İşletme Yetkilisi')], max_length=15, verbose_name='Tip'),
        ),
    ]
