# Generated by Django 2.2.1 on 2019-06-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms', '0001_initial'),
        ('branchs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Okul Numarası')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='branchs.Klass', verbose_name='Sınıf')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='terms.Term', verbose_name='Dönem')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
    ]
