# Generated by Django 2.2.1 on 2019-06-05 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190605_2246'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='member',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='members.Member'),
            preserve_default=False,
        ),
    ]
