# Generated by Django 2.2.1 on 2019-06-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='business',
        ),
    ]
